version: '3'
services:

  app:
    image: crushyna/object_detection_project:latest
    command: python -m uvicorn --host=0.0.0.0 main:app
    ports:
      - "8000:8000"
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - ./app:/app
    devices:
      - /dev/video0:/dev/video0
    privileged: true