version: '3'
services:

  app:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - ./app:/app
    devices:
      - /dev/video0:/dev/video0
    privileged: true